### ISSUE TITLE
Strange Priorities

### ISSUE THREAD

**Issue by Quantum-of-Blackness** [IIInitiationnn/BloodEmporium#9] opened 2022-11-16 16:25 UTC
I did not understand why the program chose a gold coin instead of a sports flashlight, it was noticeable at the last step. The coin has a priority of 2 and the flashlight has a priority of 3. How did it happen?

https://youtu.be/wQX8gE5D4WA

[debug-22-11-16 19-14-18.log](https://github.com/IIInitiationnn/BloodEmporium/files/10023762/debug-22-11-16.19-14-18.log)

**Comment by IIInitiationnn** [comment] 2022-11-16 19:19
Did you have the correct profile selected?
Also please note that the software is not perfectly accurate. In this case, it seems to have correctly identified everything, which suggests that maybe you didn't have the right preference profile, but until I improve the accuracy you should expect the occasional error. If you continue to have common incorrect selections, please use the current pre-release version and send me logs using that version, which may clue me into the cause.

**Comment by Quantum-of-Blackness** [comment] 2022-11-16 20:01
I seem to have chosen the right profile, I don’t know if I checked it for sure. There is another problem, if I enter this program again, the profile changes to the standard one. It would be better if the program remembers which profile was used before closing

**Comment by IIInitiationnn** [comment] 2022-11-17 08:47
Agreed, will add that functionality in the future. In the meantime, I will close this issue, feel free to reopen it if you run into problems again.

**Closed as completed by IIInitiationnn** 2022-11-17 08:47 UTC

**Comment by Quantum-of-Blackness** [comment] 2022-11-20 18:57
I had visual filters disabled and the program tried to take a perk from the edge of the web and then completely turned off
[debug-22-11-20 21-50-27.log](https://github.com/IIInitiationnn/BloodEmporium/files/10050456/debug-22-11-20.21-50-27.log)

**Comment by Quantum-of-Blackness** [comment] 2022-11-20 18:58
Is it possible to make pictures of objects in color?

**Comment by IIInitiationnn** [comment] 2022-11-20 21:10
> I had visual filters disabled and the program tried to take a perk from the edge of the web and then completely turned off [debug-22-11-20 21-50-27.log](https://github.com/IIInitiationnn/BloodEmporium/files/10050456/debug-22-11-20.21-50-27.log)

Not too sure what caused this if it's been working for a while. I'll continue to look into this but no guarantees I can resolve this with limited information.

> Is it possible to make pictures of objects in color?

Assuming you are referring to adding background colour to the items in the preference profile page (so it is easier to discern rarity, for example), that is something I am developing for an update in the near future.

**Comment by Quantum-of-Blackness** [comment] 2022-11-21 07:47
What required data is needed?

**Comment by IIInitiationnn** [comment] 2022-11-21 07:54
There is a pre-release version that you can use to supply more detailed logs.

**Comment by Quantum-of-Blackness** [comment] 2022-11-21 08:03
Do I need to replace the exe file to save my settings?

**Comment by IIInitiationnn** [comment] 2022-11-21 08:07
Yes, you can just replace the .exe file. If you don't have any personal preference profiles made using an older version, you can just unzip the new version and use it out of the box, so you can get access to the new default profiles.

**Comment by Quantum-of-Blackness** [comment] 2022-11-21 10:44
I replaced the file and the settings were not saved :(

**Comment by IIInitiationnn** [comment] 2022-11-21 20:43
All settings are stored in `config.json`. So long as you retain that file, your settings should transfer to a newer version.
