### ISSUE TITLE
Number of BPs spent continues to increment when purchasing items that you don't have enough BPs for

### ISSUE THREAD

**Issue by KevinIsMyName** [IIInitiationnn/BloodEmporium#34] opened 2023-03-29 02:14 UTC
At the end of your run where you have run out of BPs, the number of "Bloodpoints spent" continues to increment when attempting to purchase an addon/item/perk that you don't have enough BP for

**Comment by IIInitiationnn** [comment] 2023-03-29 02:42
Duplicate of #15

**Closed as not planned by IIInitiationnn** 2023-03-29 02:42 UTC
